# Travis CI (http://travis-ci.org/) is a continuous integration service for
# open source projects.

language: go

go:
    - 1.3
    - 1.4
    - tip

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y pandoc

install:
    - go get -d -t -v ./...
    - go build -v ./...

script:
    - go test -v ./...
    